# ----------------------- #
#      Main Configs       #
# ----------------------- #

url:         http://lab.whitequark.org
title:       whitequark's lab notebook
subtitle:    Documenting my work.
author:      Peter Zotov
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS subscription link
subscribe_rss: /atom.xml

# RSS feeds can list your email address if you like
email: whitequark@whitequark.org

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root:           /
permalink:      /notes/:year-:month-:day/:title/
source:         source
destination:    public
plugins:        plugins
category_dir:   notes/categories
code_dir:       .

titlecase:      false
paginate:       10                # Posts per page on the blog index
pagination_dir: notes             # Directory base for pagination URLs eg. /blog/page/2/
excerpt_link:   "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

markdown: kramdown

kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  "lsquo,rsquo,ldquo,rdquo"
  use_coderay:   false

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: []

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

github_user:    whitequark
twitter_user:   whitequark
gauges_site_id: 52fc9b0a92c6ac4ba200279e
